kodi:
  build: .
  privileged: true
  container_name: kodi
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./.kodi:./root/.kodi
    # - /var/lib/chinachu/recorded:/root/recorded:ro
  ports:
    - "8080:8080"
    - "9090:9090"
  restart: always
